# TODO (if using conda) - complete with environment name and dependencies
# Refer to the course and follow the best practices for creating a conda environment
name: abandon_env 
channels:
  - conda-forge  
  - defaults  
dependencies:
  - python=3.10 
  - pip=23.2.1  
  - pip-tools=7.3.0  
  - pip:
      - -r requirements.txt